# Generated by Django 3.0.5 on 2020-06-16 22:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightstat',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meals',
            name='currentweight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fitnessapp.weightstat'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='currentweight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fitnessapp.weightstat'),
        ),
    ]
