# Generated by Django 3.0.5 on 2020-06-16 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0002_auto_20200616_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weightstat',
            old_name='date',
            new_name='weightdate',
        ),
        migrations.AlterField(
            model_name='meals',
            name='currentweight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fitnessapp.weightstat'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='currentweight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fitnessapp.weightstat'),
        ),
    ]
